-- 0412
-- SEQUENCE에 대해 알아보자
-- 자동번호 발급해주는 객체

-- 기본 SEQUENCE 생성하기
-- CREATE SEQUENCE 시퀀스이름 [옵션] ;
-- 기본으로 생성하면 번호가 1부터 1씩 증가해서 발급해줌
-- 1. SEQUENCE 번호를 발급하려면 시퀀스명.NEXTVAL을 선언한다.
CREATE SEQUENCE SEQ_BASIC;
SELECT SEQ_BASIC.NEXTVAL FROM DUAL; -- 실행할 때마다 +1
-- SEQUENCE는 중복되지 않는 숫자를 발급해주기 때문에 테이블의 PK컬럼의 값으로 많이 사용한다.
SELECT * FROM BOARD;
DESC BOARD;
INSERT INTO BOARD VALUES(SEQ_BASIC.NEXTVAL, '첫 번째 게시글', '첫 번째', '유병승', SYSDATE);

-- 현재 SEQUENCE 값을 확인하기
-- 시퀀스명.CULLVAL를 이용한다.
SELECT SEQ_BASIC.CURRVAL FROM DUAL; -- 현재 값 확인
SELECT SEQ_BASIC.NEXTVAL FROM DUAL;

SELECT * FROM BOARD;
CREATE TABLE ATTACHMENT(
        ATTACH_NO NUMBER PRIMARY KEY,
        BOARD_REF NUMBER REFERENCES BOARD(BOARD_NO),
        FILENAME VARCHAR2(200) NOT NULL
);
INSERT INTO BOARD VALUES(SEQ_BASIC.NEXTVAL, '첨부파일게시글', '첨부파일있다', '유병승', SYSDATE);
INSERT INTO ATTACHMENT VALUES(1, SEQ_BASIC.CURRVAL, '내 사진.png');
INSERT INTO ATTACHMENT VALUES(2, SEQ_BASIC.CURRVAL, '내 사진2.png');
SELECT * FROM BOARD;
SELECT * FROM ATTACHMENT;
SELECT * FROM BOARD JOIN ATTACHMENT ON BOARD_NO = BOARD_REF;


-- SEQUENCE 옵션값 활용하기
-- START WITH 숫자 : 설정한 숫자부터 시작 DEFAULT 1
-- INCREMENT BY 숫자 : 증가하는 간격을 의미 DEFAULT 1
-- MAXVALUE 숫자 : 최대값을 설정
-- MINVALUE 숫자 : 최소값을 설정
-- CYCLE/NOCYCLE : 번호를 순환할지 말지 결정하는 것 * MAXVALUE, MINVALUE 가 설정되어 있어야한다.
-- CACHE : 미리 번호를 생성하는 기능 DEFAULT 20

-- 1. START WITH
SELECT * FROM USER_SEQUENCES;
CREATE SEQUENCE SEQ_01
START WITH 100;
SELECT SEQ_01.NEXTVAL FROM DUAL;

-- 2. INCREMENT BY
CREATE SEQUENCE SEQ_02
START WITH 100
INCREMENT BY 10;
SELECT SEQ_02.NEXTVAL FROM DUAL;

-- 3. MAXVALUE/MINVALUE
CREATE SEQUENCE SEQ_03
START WITH 100
INCREMENT BY -50
MAXVALUE 200
MINVALUE 0;
SELECT SEQ_03.NEXTVAL FROM DUAL;

-- 4. CYCLE/NOCYCLE + 5. CACHE
CREATE SEQUENCE SEQ_04
START WITH 100
INCREMENT BY 50
MAXVALUE 200
MINVALUE 0
CYCLE
NOCACHE;
SELECT SEQ_04.NEXTVAL FROM DUAL;

-- 1. CURRVAL를 호출하려면 같은 SESSION안에서 NEXTVAL를 한 번이라도 호출하고 호출해야 한다.
CREATE SEQUENCE SEQ_05;
SELECT SEQ_05.CURRVAL FROM DUAL; -- 실행불가
SELECT SEQ_05.NEXTVAL, SEQ_05.CURRVAL FROM DUAL;

-- 2. SEQUENCE에 값을 추가해서 PK값으로 쓸 수 있다.
-- P_001, M_001
SELECT 'P_' || LPAD(SEQ_05.NEXTVAL, 4, '0') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') || '_' || SEQ_05.NEXTVAL FROM DUAL;

-- 오라클에서 제공하는 SELECT문
-- 계층형쿼리, 한 테이블에서 연관있는 ROW를 묶어서 출력할 수 있게 해주는 쿼리문
--  -> ROW순서를 연관있는 자료로 연결해서 출력
-- 매니저와 연결해서 출력하기
SELECT LEVEL, EMP_ID, EMP_NAME, MANAGER_ID
FROM EMPLOYEE
        START WITH EMP_ID = 200 -- ROOT 최상(LEVEL = 1, 연결된 ROW 2 , 다음 연결된 ROW 3)
        CONNECT BY PRIOR EMP_ID = MANAGER_ID;

SELECT LEVEL || ' ' || LPAD(' ', (LEVEL -1)*5, ' ') || EMP_NAME || NVL2(MANAGER_ID, '(' || MANAGER_ID || ')' , '') AS 조직도
FROM EMPLOYEE
        START WITH EMP_ID = 200
        CONNECT BY PRIOR EMP_ID = MANAGER_ID;